CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author TEXT,
    description TEXT,
    image_url TEXT,
    isbn TEXT,
    is_bestseller BOOLEAN,
    rating FLOAT,
    title TEXT,
    publication_year INTEGER,
    PRIMARY KEY (id)
);

CREATE TABLE book_tags (
    book_id BIGINT NOT NULL,
    tags TEXT NOT NULL,
    FOREIGN KEY (book_id) REFERENCES book(id)
);
